apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
      - name: backend-db
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: Mobiles
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: backend-db-service
spec:
  selector:
    app: backend-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: NodePort
