apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /home/spoofy/pv
  storageClassName: abc
  persistentVolumeReclaimPolicy: Delete