kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template: 
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: deployment-container
        image: usama9876/firstdocker-app

---
apiVersion: v1
kind: Service
metadata:
  name: deploy-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
  selector:
    tier: frontend
