kind: Pod
apiVersion: v1
metadata:
  name: liveprob 
spec:
  containers:
  - name: container-1
    image: usama9876/firstdocker-app
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
        - ls
