kind: Pod
apiVersion: v1
metadata:
  name: liveprob3
spec:
  containers:
  - name: container-1
    image: usama9876/firstdocker-app
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80 
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 10
      timeoutSeconds: 1
      initialDelaySeconds: 10

