kind: Pod
apiVersion: v1
metadata:
  name: readyprobe
spec:
  containers: 
  - name: container-1
    image: usama9876/firstdocker-app
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 90
