apiVersion: v1
kind: Pod
metadata: 
  name: pod-pv
spec:
  volumes:
  - name: pvol
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - name: cont-one
    image: usama9876/firstdocker-app
    volumeMounts:
    - name: pvol
      mountPath: /tmp/demo
