kind: CronJob
apiVersion: batch/v1
metadata: 
  name: mycronjob
spec:
  schedule: "* * * * *"
  jobTemplate: 
    spec:
      template: 
        spec:
          containers:
          - name: job-container
            image: usama9876/firstdocker-app
         restartPolicy: Never 
      
