apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-processor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-processor-role
subjects:
- kind: ServiceAccount
  name: your-service-account
