apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
spec:
  template:
    spec:
      containers:
      - name: data-processor
        image: your-data-processing-image:tag
        # Add other container settings and environment variables as needed
      restartPolicy: Never
