kind: Pod
apiVersion: v1
metadata:
  name: newpod
  labels:
    type: backend
    env: tier2
spec:
  containers:
  - name: container-1
    image: usama9876/firstdocker-app
    ports:
    -  containerPort: 80
