apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
spec:
  template:
    metadata:
      name: data-processing-pod
    spec:
      containers:
      - name: data-processor
        image: busybox:latest
        # Add other container specifications (environment variables, etc.)
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume-claim
