apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-processing-cronjob
spec:
  schedule: "* * * * *"  # Cron expression for running every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-processor
            image: busybox:latest
           
          restartPolicy: Never
