apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Modify as needed
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5432 # Replace with your backend service port
      targetPort: 5432 # Replace with your backend service port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: your-backend-image:latest
        ports:
        - containerPort: 5432 # Replace with your backend service port
        # Add other necessary specifications (env, volume mounts, etc.)
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data # Adjust based on your database requirements
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc

